spring:
  application:
    name: get_jobs
  profiles:
    active: dev
  info:
    app:
      name: Get Jobs
      version: 0.0.1-SNAPSHOT
      description: https://github.com/loks666/get_jobs
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  datasource:
    url: jdbc:sqlite:./db/config.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-test-query: SELECT 1

    datasource-data:
      url: jdbc:sqlite:./db/data.db
      driver-class-name: org.sqlite.JDBC
      hikari:
        maximum-pool-size: 1
        connection-test-query: SELECT 1
  sql:
    init:
      mode: never  # 数据库文件已存在，不需要自动初始化
  output:
    ansi:
      enabled: always

# 服务器配置
server:
  port: 8888

# 日志配置
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr(%logger{36}){cyan} %clr(-){faint} %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./target/logs/get-jobs.log   # 当前日志文件，不要日期
  logback:
    rollingpolicy:
      file-name-pattern: ./target/logs/get-jobs.%d{yyyy-MM-dd}.log
      max-history: 30

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
